name: Build app

on: push

jobs: 
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Use Node.js -v 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build